Add command to initialize storage

diff --git a/vagga/load_fixture.yaml b/vagga/load_fixture.yaml
--- a/vagga/load_fixture.yaml
+++ b/vagga/load_fixture.yaml
@@ -1,16 +1,20 @@
-mysqld_safe --skip-syslog --no-auto-restart
-while [ ! -f /tmp/mysqld.pid ]; do sleep 0.1; done
-if [ "$#" = 1 ] ; then
-  case "$1" in
+|
+  mysqld_safe --skip-syslog --no-auto-restart
+  while [ ! -f /tmp/mysqld.pid ]; do sleep 0.1; done
+  case "$0" in
     *.gz )
-      echo "Loading compressed data from $1"
+      echo "Loading compressed data from $0"
       viewer=zcat
       ;;
-    *)
-      echo "Loading raw data from $1"
+    *.sql)
+      echo "Loading raw data from $0"
       viewer=cat
       ;;
+    *)
+      echo "Wrong fixture format or missing file"
+      mysqladmin shutdown
+      exit 1
+      ;;
   esac
-  $viewer $1 | mysql --user=$DB_USERNAME --password=$DB_PASSWORD --database=$DB_DATABASE
-fi
-mysqladmin shutdown
+  $viewer $0 | mysql --user=$DB_USERNAME --password=$DB_PASSWORD --database=$DB_DATABASE
+  mysqladmin shutdown
